global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NestJS uygulamanız için metrics endpoint'i
  - job_name: 'nestjs-app'
    static_configs:
      - targets: ['host.docker.internal:3000']  # macOS için
      - targets: ['172.17.0.1:3000']  # Linux için alternatif
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
